[package]
name = "copper-substrate"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"

egui = { workspace = true }
eframe = { workspace = true }

egui_lens = "0.1.0"
local-ip = "0.1.0"
uuid = { version = "1.11", features = ["v4"] }

